export const JOIN_ROOM_START = 'JOIN_ROOM_START';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';
export const JOIN_ROOM_FAILURE = 'JOIN_ROOM_FAILURE';

export const SAVE_MESSAGE_START = 'SAVE_MESSAGE_START';
export const SAVE_MESSAGE_SUCCESS = 'SAVE_MESSAGE_SUCCESS';
export const SAVE_MESSAGE_FAILURE = 'SAVE_MESSAGE_FAILURE';

export const FETCH_ROOM_MESSAGES = 'FETCH_ROOM_MESSAGES';
export const FETCH_ROOM_MESSAGES_SUCCESS = 'FETCH_ROOM_MESSAGES_SUCCESS';
export const FETCH_ROOM_MESSAGES_FAILURE = 'FETCH_ROOM_MESSAGES_FAILURE';

export const CLEAR_CHAT_ROOM = 'CLEAR_CHAT_ROOM';

export const CHANGE_ROOM = 'CHANGE_ROOM';
